### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by ahill6** [ahill6/Research#8]
- [ ] Run econ model for set of SE projects ranging from old-fashioned waterfall to new fangled agile?
- [ ] Add signaling horror story to beginning
- [ ] Remove all basically/essentially
- [ ] Move XOMO from related work
- [ ] Add reference to to statement about pace of change yielding out-of-touch models
- [ ] Add micro-assumptions explicitly to commissioning a model
- [ ] Make picture of BUS model (i.e. add visualization)
- [ ] Add assertion of BUS authority
- [ ] Move validation of micro-assumptions (MAs) to commissioning a model
- [ ] Move introduction of MAs to beginning of section 3
- [ ] Add more references to all model descriptions
- [ ] Misc. minor edits
- [ ] Figure out which journal to submit to (JSS/TSE?)
- [ ] Add results w.r.t. agile vs waterfall vs hybrid
- [ ] Color cell, not text for negatives
- [ ] Log scale for runtimes (only need one runtime graph) AND change references to match
- [ ] Add 2-3 citations each for models from Raffo, Boehm, Port/Menzies
- [ ] Statement about waterfall vs agile?
